import { User, GLAccount, UserRole, ReviewStatus } from './types';

export const USERS: User[] = [
  { id: 1, name: 'Alice', role: UserRole.Checker1 },
  { id: 2, name: 'Bob', role: UserRole.Checker2 },
  { id: 3, name: 'Charlie', role: UserRole.Checker3 },
  { id: 4, name: 'Diana', role: UserRole.Checker4 },
  { id: 5, name: 'Eve', role: UserRole.CFO },
];

export const INITIAL_ACCOUNTS: GLAccount[] = [
    {
        id: 1,
        glAccountNumber: '101000',
        glAccount: 'Cash and Cash Equivalents',
        responsibleDept: 'Finance',
        departmentId: 'FIN001',
        logicId: 'FIN-CORE-0001',
        mainHead: 'Assets',
        subHead: 'Current Assets',
        bsPl: 'BS',
        statusCategory: 'Assets',
        spoc: 'John Doe',
        reviewer: 'Jane Smith',
        reviewStatus: ReviewStatus.Pending,
        currentChecker: UserRole.Checker1,
        auditLog: [
            {
                timestamp: new Date('2023-10-01T10:00:00Z').toISOString(),
                user: 'System',
                role: UserRole.Checker1,
                action: 'Data Ingestion',
                from: 'N/A',
                to: UserRole.Checker1,
            },
        ],
        mistakeCount: 0,
        reportUrl: 'https://example.com/reports/101000.pdf',
        classificationConfidence: 0.96,
        classificationSource: 'historical',
        classificationEvidence: [
            {
                type: 'historical',
                value: 'SeedMapping:101000',
                weight: 1,
                confidence: 0.96,
            },
            {
                type: 'keyword',
                value: 'cash',
                weight: 0.4,
                confidence: 0.8,
            },
        ],
        classificationNotes: 'Mapped to Finance treasury cluster based on historical configuration.',
        classificationKeywords: ['cash', 'equivalents'],
        classificationPatterns: ['^101'],
        inputDepartment: 'Treasury',
        balanceRaw: '1,250,000.00',
        normalizedBalance: 1250000,
        currency: 'INR',
        balanceIssues: [],
        balanceDate: new Date('2023-09-30').toISOString(),
        thresholdLevel: 'M',
        priorityScore: 0.74,
        varianceAgainstPrevious: 0.03,
        frequencyBucket: 'M',
    },
    {
        id: 2,
        glAccountNumber: '121000',
        glAccount: 'Accounts Receivable',
        responsibleDept: 'Sales',
        departmentId: 'SAL001',
        logicId: 'SAL-REV-0001',
        mainHead: 'Assets',
        subHead: 'Current Assets',
        bsPl: 'BS',
        statusCategory: 'Assets',
        spoc: 'Peter Pan',
        reviewer: 'Wendy Darling',
        reviewStatus: ReviewStatus.Pending,
        currentChecker: UserRole.Checker2,
        auditLog: [
             {
                timestamp: new Date('2023-10-01T10:00:00Z').toISOString(),
                user: 'System',
                role: UserRole.Checker1,
                action: 'Data Ingestion',
                from: 'N/A',
                to: UserRole.Checker1,
            },
            {
                timestamp: new Date('2023-10-02T11:00:00Z').toISOString(),
                user: 'Alice',
                role: UserRole.Checker1,
                action: 'Approved by Checker 1',
                from: UserRole.Checker1,
                to: UserRole.Checker2,
            },
        ],
        mistakeCount: 0,
        reportUrl: 'https://example.com/reports/121000.pdf',
        classificationConfidence: 0.93,
        classificationSource: 'historical',
        classificationEvidence: [
            {
                type: 'historical',
                value: 'SeedMapping:121000',
                weight: 1,
                confidence: 0.93,
            },
            {
                type: 'keyword',
                value: 'receivable',
                weight: 0.35,
                confidence: 0.75,
            },
        ],
        classificationNotes: 'Receivable balances align with Sales collections function.',
        classificationKeywords: ['receivable', 'sales'],
        classificationPatterns: ['^121'],
        inputDepartment: 'Sales',
        balanceRaw: '890,000.00',
        normalizedBalance: 890000,
        currency: 'INR',
        balanceIssues: [],
        balanceDate: new Date('2023-09-30').toISOString(),
        thresholdLevel: 'M',
        priorityScore: 0.68,
        varianceAgainstPrevious: -0.02,
        frequencyBucket: 'M',
    },
    {
        id: 3,
        glAccountNumber: '201000',
        glAccount: 'Accounts Payable',
        responsibleDept: 'Procurement',
        departmentId: 'PUR001',
        logicId: 'PUR-LIAB-0003',
        mainHead: 'Liabilities',
        subHead: 'Current Liabilities',
        bsPl: 'BS',
        statusCategory: 'Liabilities',
        spoc: 'Captain Hook',
        reviewer: 'Smee',
        reviewStatus: ReviewStatus.Mismatch,
        currentChecker: UserRole.Checker1,
        auditLog: [
            {
                timestamp: new Date('2023-10-01T10:00:00Z').toISOString(),
                user: 'System',
                role: UserRole.Checker1,
                action: 'Data Ingestion',
                from: 'N/A',
                to: UserRole.Checker1,
            },
            {
                timestamp: new Date('2023-10-02T12:00:00Z').toISOString(),
                user: 'Alice',
                role: UserRole.Checker1,
                action: 'Approved by Checker 1',
                from: UserRole.Checker1,
                to: UserRole.Checker2,
            },
            {
                timestamp: new Date('2023-10-03T14:00:00Z').toISOString(),
                user: 'Bob',
                role: UserRole.Checker2,
                action: 'Rejected by Checker 2',
                from: UserRole.Checker2,
                to: UserRole.Checker1,
                reason: 'Invoice amount does not match PO.',
            },
        ],
        mistakeCount: 1,
        reportUrl: '',
        classificationConfidence: 0.91,
        classificationSource: 'historical',
        classificationEvidence: [
            {
                type: 'historical',
                value: 'SeedMapping:201000',
                weight: 1,
                confidence: 0.91,
            },
            {
                type: 'keyword',
                value: 'payable',
                weight: 0.4,
                confidence: 0.78,
            },
        ],
        classificationNotes: 'Liability account maintained by Procurement/AP operations.',
        classificationKeywords: ['payable', 'accounts'],
        classificationPatterns: ['^201'],
        inputDepartment: 'Procurement',
        balanceRaw: '(625,000.00)',
        normalizedBalance: -625000,
        currency: 'INR',
        balanceIssues: [],
        balanceDate: new Date('2023-09-30').toISOString(),
        thresholdLevel: 'C',
        priorityScore: 0.92,
        varianceAgainstPrevious: 0.07,
        frequencyBucket: 'C',
    },
    {
        id: 4,
        glAccountNumber: '401000',
        glAccount: 'Sales Revenue',
        responsibleDept: 'Sales',
        departmentId: 'SAL001',
        logicId: 'SAL-REV-0401',
        mainHead: 'Revenue',
        subHead: 'Operating Revenue',
        bsPl: 'PL',
        statusCategory: 'Revenue',
        spoc: 'Mickey Mouse',
        reviewer: 'Minnie Mouse',
        reviewStatus: ReviewStatus.Finalized,
        currentChecker: null,
        auditLog: [
            {
                timestamp: new Date('2023-09-25T10:00:00Z').toISOString(),
                user: 'System',
                role: UserRole.Checker1,
                action: 'Data Ingestion',
                from: 'N/A',
                to: UserRole.Checker1,
            },
            {
                timestamp: new Date('2023-09-26T11:00:00Z').toISOString(),
                user: 'Alice',
                role: UserRole.Checker1,
                action: 'Approved by Checker 1',
                from: UserRole.Checker1,
                to: UserRole.Checker2,
            },
            {
                timestamp: new Date('2023-09-27T12:00:00Z').toISOString(),
                user: 'Bob',
                role: UserRole.Checker2,
                action: 'Approved by Checker 2',
                from: UserRole.Checker2,
                to: UserRole.Checker3,
            },
            {
                timestamp: new Date('2023-09-28T13:00:00Z').toISOString(),
                user: 'Charlie',
                role: UserRole.Checker3,
                action: 'Approved by Checker 3',
                from: UserRole.Checker3,
                to: UserRole.Checker4,
            },
            {
                timestamp: new Date('2023-09-29T14:00:00Z').toISOString(),
                user: 'Diana',
                role: UserRole.Checker4,
                action: 'Approved by Checker 4',
                from: UserRole.Checker4,
                to: 'Finalized',
            },
        ],
        mistakeCount: 0,
        reportUrl: 'https://example.com/reports/401000.pdf',
        classificationConfidence: 0.97,
        classificationSource: 'historical',
        classificationEvidence: [
            {
                type: 'historical',
                value: 'SeedMapping:401000',
                weight: 1,
                confidence: 0.97,
            },
            {
                type: 'keyword',
                value: 'sales revenue',
                weight: 0.45,
                confidence: 0.86,
            },
        ],
        classificationNotes: 'Revenue recognition governed by Sales operations.',
        classificationKeywords: ['sales', 'revenue'],
        classificationPatterns: ['^401'],
        inputDepartment: 'Sales',
        balanceRaw: '3,450,000.00',
        normalizedBalance: 3450000,
        currency: 'INR',
        balanceIssues: [],
        balanceDate: new Date('2023-09-30').toISOString(),
        thresholdLevel: 'L',
        priorityScore: 0.56,
        varianceAgainstPrevious: 0.1,
        frequencyBucket: 'L',
    },
    {
        id: 5,
        glAccountNumber: '505000',
        glAccount: 'Cost of Goods Sold',
        responsibleDept: 'Operations',
        departmentId: 'OPR001',
        logicId: 'OPS-COGS-0505',
        mainHead: 'Expenses',
        subHead: 'Operating Expenses',
        bsPl: 'PL',
        statusCategory: 'Expenses',
        spoc: 'Donald Duck',
        reviewer: 'Daisy Duck',
        reviewStatus: ReviewStatus.Approved,
        currentChecker: UserRole.Checker4,
        auditLog: [
            {
                timestamp: new Date('2023-10-01T10:00:00Z').toISOString(),
                user: 'System',
                role: UserRole.Checker1,
                action: 'Data Ingestion',
                from: 'N/A',
                to: UserRole.Checker1,
            },
            {
                timestamp: new Date('2023-10-02T11:00:00Z').toISOString(),
                user: 'Alice',
                role: UserRole.Checker1,
                action: 'Approved by Checker 1',
                from: UserRole.Checker1,
                to: UserRole.Checker2,
            },
             {
                timestamp: new Date('2023-10-03T12:00:00Z').toISOString(),
                user: 'Bob',
                role: UserRole.Checker2,
                action: 'Approved by Checker 2',
                from: UserRole.Checker2,
                to: UserRole.Checker3,
            },
             {
                timestamp: new Date('2023-10-04T13:00:00Z').toISOString(),
                user: 'Charlie',
                role: UserRole.Checker3,
                action: 'Approved by Checker 3',
                from: UserRole.Checker3,
                to: UserRole.Checker4,
            }
        ],
        mistakeCount: 0,
        reportUrl: 'https://example.com/reports/505000.pdf',
        classificationConfidence: 0.9,
        classificationSource: 'historical',
        classificationEvidence: [
            {
                type: 'historical',
                value: 'SeedMapping:505000',
                weight: 1,
                confidence: 0.9,
            },
            {
                type: 'keyword',
                value: 'cost of goods',
                weight: 0.4,
                confidence: 0.8,
            },
        ],
        classificationNotes: 'COGS tracked under core operations team.',
        classificationKeywords: ['cogs', 'cost of goods'],
        classificationPatterns: ['^505'],
        inputDepartment: 'Operations',
        balanceRaw: '(2,150,000.00)',
        normalizedBalance: -2150000,
        currency: 'INR',
        balanceIssues: [],
        balanceDate: new Date('2023-09-30').toISOString(),
        thresholdLevel: 'M',
        priorityScore: 0.81,
        varianceAgainstPrevious: -0.05,
        frequencyBucket: 'M',
    }
].sort((a, b) => {
    const nameCompare = a.glAccount.localeCompare(b.glAccount, undefined, { sensitivity: 'base' });
    if (nameCompare !== 0) {
        return nameCompare;
    }
    const deptCompare = a.responsibleDept.localeCompare(b.responsibleDept, undefined, { sensitivity: 'base' });
    if (deptCompare !== 0) {
        return deptCompare;
    }
    return a.glAccountNumber.localeCompare(b.glAccountNumber, undefined, { sensitivity: 'base' });
});
